# Site settings
title: MBA Brothers
email: admin@mbabros.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:mbabros

# Build settings
markdown: kramdown
